# TODO: Move this to a different git repo
version: "3.7"

services:
  load-balancer:
    image: nginx
    networks:
      - load-balancer
    ports:
      - "8080:80"
    configs:
      - target: /etc/nginx/nginx.conf
        source: nginx-conf-7
    deploy:
      replicas: 1

  placehodor:
    image: github.com/danpantry/www.placehodor.io
    networks:
      - load-balancer
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=8080
    deploy:
      replicas: 1

configs:
  nginx-conf-7:
    file: etc/nginx/nginx.conf

networks:
  load-balancer:
    driver: overlay
    attachable: true
